# See https://github.com/jj-vcs/jj/discussions/5812.

"$schema" = 'https://jj-vcs.github.io/jj/prerelease/config-schema.json'

[user]
name = 'John Koelndorfer'
# e-mail is configured per repository

[revset-aliases]
'trunk()' = 'latest((present(master) | present(main)) & remote_bookmarks())'

'stack()' = 'ancestors(reachable(@, mutable()), 2)'
'stack(x)' = 'ancestors(reachable(x, mutable()), 2)'
'stack(x, n)' = 'ancestors(reachable(x, mutable()), n)'

[aliases]
mark = ["util", "exec", "--", "jj-mark"]
push = ["util", "exec", "--", "jj-mark", "--push"]
retrunk = ["util", "exec", "--", "jj-fetch-rebase", "-d", "trunk()"]
